from os.path import join, abspath
from collections import deque
from pathlib import Path
from itertools import chain, zip_longest
from typing import NoReturn, Union, NewType

from datetime import datetime

from reportlab.platypus import Table, SimpleDocTemplate, Frame, TableStyle, Paragraph
from reportlab.lib.colors import red, yellow, gainsboro, darkgray, black, snow, HexColor
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.utils import ImageReader
from reportlab.pdfgen.canvas import Canvas
from reportlab.lib.units import cm, inch
from reportlab.lib.pagesizes import letter

ReportCanvas = NewType("ReportCanvas", Canvas)

dated = datetime.today().strftime("%d-%m-%Y %X")
filenamed = "viva_id_report" +"_"+ dated+".pdf"


class GenerateReport(object):
    def __init__(self):
        self.canvas = None
        self.width = 1024
        self.height = 900
        self.response = {"msg": None, "result": False}

    def set_canvas(self) -> NoReturn:
        p = Path().home()
        report_file_path = str(p) + str(p.joinpath("/Documents/")) + f"/{filenamed}"
        self.canvas = Canvas(report_file_path, [self.width, self.height])

    def set_font(self) -> NoReturn:
        self.canvas.setFont("Helvetica", 12)

    def set_stroke_color(self) -> NoReturn:
        self.canvas.setStrokeColorRGB(0.2, 0.5, 0.3)

    def set_background(self) -> NoReturn:
        self.canvas.linearGradient(0, 0, 1024, 900, (snow, gainsboro, gainsboro), positions=(0, 0.7, 1), extend=False)
        self.canvas.saveState()

    def set_canvas_to_cms(self) -> NoReturn:
        self.canvas.translate(cm, cm)

    def set_pdf_title(self) -> NoReturn:
        self.canvas.setTitle("Vivo ID Report System")

    def set_header(self) -> NoReturn:
        self.canvas.setFont("Times-Roman", 24)
        self.canvas.drawRightString(950, 800, "Vivo ID Report")

    def set_report_date(self) -> NoReturn:
        self.canvas.setFont("Courier", 14)
        self.canvas.drawRightString(950, 770, f"Report On: {dated}")

    def set_pdf_subject(self) -> NoReturn:
        self.canvas.setTitle("Report")

    def set_pdf_creator(self) -> NoReturn:
        self.canvas.setCreator("Vivo ID Report System")

    def set_logo(self) -> NoReturn:
        logo = ImageReader("/home/platoschild/PythonProjects/student_management_system/icons/vivo_logo.png")
        self.canvas.drawImage(logo, 0, 750, width=100, height=100, mask="auto")

    def render_table(self, canvas: ReportCanvas, data: Union[None, list]) -> NoReturn:
        self.canvas.restoreState()
        table = Table(data)
        table.setStyle(
            TableStyle(
                [
                    ("GRID", (0, 0), (-1, -1), 1, black),
                    ('BOX', (0, 0), (-1, -5), 1, black),
                    ("FONT", (0, 0), (-1, -1), "Courier", 15)
                ]
            )
        )
        data_len = len(data)
        even_row_color = HexColor("#D7E1EC")
        odd_row_color = HexColor("#D9D9D9")

        for row in range(data_len):
            if row % 2 == 0:
                row_color = even_row_color
            else:
                row_color = odd_row_color

            table.setStyle(
                TableStyle(
                    [
                        ('BACKGROUND', (0, row), (-1, row), row_color)
                    ]
                )
            )
        w, h = table.wrapOn(self.canvas, 1000, 900)
        table.drawOn(canvas, 50, 20)

    def set_rect1(self) -> NoReturn:
        first_color = HexColor("#f8f9d2")
        self.canvas.setFillColor(first_color)
        self.canvas.rect(5, 0, 40, 40, stroke=0, fill=1)

    def set_rect2(self) -> NoReturn:
        second_color = HexColor("#e8dbfc")
        self.canvas.setFillColor(second_color)
        self.canvas.rect(5, 0, 30, 30, stroke=0, fill=1)

    def set_description(self) -> NoReturn:
        styles = getSampleStyleSheet()
        description_style = styles["BodyText"]
        description = Paragraph(
            "<bold>\
                <font size=18>Student IDs Processing Report</font>\
                <br/>\
                <br/>\
                <font size=14><span>This Report Is Generated by <i>Vivo ID Report System</i>. The following data is tabulated from the data store and serves to show students id status.</span></font>\
            </bold>",
            description_style
        )
        w, h = description.wrap(1000, 900)
        description.drawOn(self.canvas, 72, 700)

    def show_page(self) -> NoReturn:
        self.canvas.showPage()

    def save_page(self) -> NoReturn:
        self.canvas.save()

    def setup(self) -> NoReturn:
        [func for func in [
            self.set_canvas(),
            self.set_canvas_to_cms(),
            self.set_background(),
            self.set_stroke_color(),
            self.set_font(),
            self.set_header(),
            self.set_report_date(),
            self.set_pdf_title(),
            self.set_pdf_creator(),
            self.set_pdf_subject(),
            self.set_logo(),
            self.set_rect1(),
            self.set_rect2(),
            self.set_description()
            ]
        ]

    def parse_data(self, data: Union[None, list]) -> list:
        parsed_data_result = deque()
        if data is None:
            return None
        else:
            for i in data:
                parsed_data_result.append(list(chain.from_iterable([[id_, first_name, surname, course, status, registered_on, expiry_date] for id_, first_name, surname, course, status, registered_on, expiry_date in zip_longest([i["id"]], [i["first_name"]], [i["surname"]], [i["course"]], [i["status"]], [i["registered_on"]], [i["expiry_date"]])])))
            parsed_data_result.appendleft(["ID", "FIRST NAME", "SURNAME", "COURSE", "STATUS", "REGISTERED ON", "EXPIRY DATE"])
            return list(parsed_data_result)

    def generate_report(self, table_data: list = None) -> NoReturn:
        if table_data:
            try:
                self.setup()
            except:
                self.response["msg"] = "Error occurred while setting up Viva ID Report"
                return self.response
            else:
                self.response["msg"] = "Generated Report Successfully"
                self.response["result"] = True
                return self.response
            finally:
                data = self.parse_data(table_data)
                self.render_table(self.canvas, data)
                self.show_page(),
                self.save_page()
        else:
            self.response["msg"] = "Report not generated. Empty Table data"
            return self.response

#
# if __name__ == "__main__":
#     data = [
#         {
#             "branch": "Langata",
#             "course": "Bsc.Computer Science",
#             "department": "Computer Science",
#             "expiry_date": "23-08-2024",
#             "first_name": "Mike",
#             "id": 1022030,
#             "registered_on": "20-08-2020",
#             "status": "pending",
#             "surname": "Mulwa"
#         },
#         {
#             "branch": "Langata",
#             "course": "Bsc.Computer Science",
#             "department": "Computer Science",
#             "expiry_date": "23-08-2024",
#             "first_name": "Josephine",
#             "id": 1022031,
#             "registered_on": "20-08-2020",
#             "status": "active",
#             "surname": "Labos"
#         },
#         {
#             "branch": "Eldoret",
#             "course": "B.A(Econ).Economics",
#             "department": "Economics",
#             "expiry_date": "20-08-2024",
#             "first_name": "Risper",
#             "id": 1022032,
#             "registered_on": "20-08-2020",
#             "status": "active",
#             "surname": "Chikwekwe"
#         },
#         {
#             "branch": "Nairobi CBD",
#             "course": "Dip.IT",
#             "department": "Computer Science",
#             "expiry_date": "23-08-2024",
#             "first_name": "James",
#             "id": 1022033,
#             "registered_on": "20-08-2020",
#             "status": "active",
#             "surname": "Kairu"
#         },
#         {
#             "branch": "Langata",
#             "course": "M.Ed.Education",
#             "department": "Education",
#             "expiry_date": "23-08-2024",
#             "first_name": "millicent",
#             "id": 1022034,
#             "registered_on": "21-08-2020 16:49:47",
#             "status": "active",
#             "surname": "kuria"
#         },
#         {
#             "branch": "Langata",
#             "course": "Bsc.Computer Science",
#             "department": "Computer Science",
#             "expiry_date": "23-08-2024",
#             "first_name": "jane",
#             "id": 1022035,
#             "registered_on": "22-08-2020 12:01:07",
#             "status": "deactivated",
#             "surname": "goiri"
#         },
#         {
#             "branch": "Langata",
#             "course": "Bsc.Computer Science",
#             "department": "Computer Science",
#             "expiry_date": "23-08-2024",
#             "first_name": "john",
#             "id": 1022036,
#             "registered_on": "22-08-2020 12:32:29",
#             "status": "pending",
#             "surname": "williams"
#         },
#         {
#             "branch": "Langata",
#             "course": "Bsc.Computer Science",
#             "department": "Computer Science",
#             "expiry_date": "23-08-2024",
#             "first_name": "crispus",
#             "id": 1022037,
#             "registered_on": "22-08-2020 12:32:29",
#             "status": "active",
#             "surname": "jean"
#         },
#         {
#             "branch": "Langata",
#             "course": "Bsc.Computer Science",
#             "department": "Computer Science",
#             "expiry_date": "23-08-2024",
#             "first_name": "chris",
#             "id": 1022038,
#             "registered_on": "23-08-2020 14:03:38",
#             "status": "active",
#             "surname": "nandasaba"
#         },
#         {
#             "branch": "Nairobi CBD",
#             "course": "PgDip.Divinity",
#             "department": "Theology",
#             "expiry_date": "26-08-2024",
#             "first_name": "William",
#             "id": 1022039,
#             "registered_on": "26-08-2020 12:14:47",
#             "status": "active",
#             "surname": "Mirugi"
#         },
#         {
#             "branch": "Langata",
#             "course": "Bsc.Computer Science",
#             "department": "Computer Science",
#             "expiry_date": "03-09-2024",
#             "first_name": "martin",
#             "id": 1022040,
#             "registered_on": "03-09-2020 11:00:04",
#             "status": "active",
#             "surname": "ndirangu"
#         },
#         {
#             "branch": "Langata",
#             "course": "Bsc.Computer Science",
#             "department": "Computer Science",
#             "expiry_date": "03-09-2024",
#             "first_name": "mike ",
#             "id": 1022041,
#             "registered_on": "03-09-2020 11:04:58",
#             "status": "active",
#             "surname": "lugonzo"
#         },
#         {
#             "branch": "Langata",
#             "course": "Bsc.Computer Science",
#             "department": "Computer Science",
#             "expiry_date": "03-09-2024",
#             "first_name": "joyce ",
#             "id": 1022042,
#             "registered_on": "03-09-2020 11:10:52",
#             "status": "active",
#             "surname": "laboso"
#         },
#         {
#             "branch": "Langata",
#             "course": "Bsc.Computer Science",
#             "department": "Computer Science",
#             "expiry_date": "03-09-2024",
#             "first_name": "Kyle ",
#             "id": 1022043,
#             "registered_on": "03-09-2020 12:10:12",
#             "status": "pending",
#             "surname": "Michugi"
#         },
#         {
#             "branch": "Langata",
#             "course": "Bsc.Computer Science",
#             "department": "Computer Science",
#             "expiry_date": "03-09-2024",
#             "first_name": "kiloo",
#             "id": 1022044,
#             "registered_on": "03-09-2020 12:10:12",
#             "status": "active",
#             "surname": "alpha"
#         },
#         {
#             "branch": "Langata",
#             "course": "Bsc.Computer Science",
#             "department": "Computer Science",
#             "expiry_date": "03-09-2024",
#             "first_name": "xxxfsf",
#             "id": 1022045,
#             "registered_on": "03-09-2020 12:10:12",
#             "status": "deactivated",
#             "surname": "svsvsg"
#         },
#         {
#             "branch": "Langata",
#             "course": "Bsc.Computer Science",
#             "department": "Computer Science",
#             "expiry_date": "03-09-2024",
#             "first_name": "peter",
#             "id": 1022046,
#             "registered_on": "03-09-2020 12:15:58",
#             "status": "deactivated",
#             "surname": "kosmos"
#         },
#         {
#             "branch": "Langata",
#             "course": "Bsc.Computer Science",
#             "department": "Computer Science",
#             "expiry_date": "03-09-2024",
#             "first_name": "joyce",
#             "id": 1022047,
#             "registered_on": "03-09-2020 12:17:53",
#             "status": "pending",
#             "surname": "lugonzo"
#         },
#         {
#             "branch": "Langata",
#             "course": "Bsc.Computer Science",
#             "department": "Computer Science",
#             "expiry_date": "03-09-2024",
#             "first_name": "poakfpoak",
#             "id": 1022048,
#             "registered_on": "03-09-2020 12:19:50",
#             "status": "pending",
#             "surname": "amalkvalvmk"
#         },
#         {
#             "branch": "Langata",
#             "course": "Bsc.Computer Science",
#             "department": "Computer Science",
#             "expiry_date": "03-09-2024",
#             "first_name": "slkafak",
#             "id": 1022049,
#             "registered_on": "03-09-2020 12:28:12",
#             "status": "pending",
#             "surname": "a;a;lfa;lfk"
#         },
#         {
#             "branch": "Langata",
#             "course": "Bsc.Computer Science",
#             "department": "Computer Science",
#             "expiry_date": "03-09-2024",
#             "first_name": "svsv",
#             "id": 1022050,
#             "registered_on": "03-09-2020 12:31:23",
#             "status": "deactivated",
#             "surname": "ssgga"
#         },
#         {
#             "branch": "Langata",
#             "course": "Bsc.Computer Science",
#             "department": "Computer Science",
#             "expiry_date": "03-09-2024",
#             "first_name": "jknkln",
#             "id": 1022051,
#             "registered_on": "03-09-2020 12:49:57",
#             "status": "active",
#             "surname": "klmm;lm"
#         },
#         {
#             "branch": "Langata",
#             "course": "Bsc.Computer Science",
#             "department": "Computer Science",
#             "expiry_date": "03-09-2024",
#             "first_name": "svsbsb",
#             "id": 1022052,
#             "registered_on": "03-09-2020 12:52:33",
#             "status": "pending",
#             "surname": "bsbbab"
#         },
#         {
#             "branch": "Langata",
#             "course": "Bsc.Computer Science",
#             "department": "Computer Science",
#             "expiry_date": "03-09-2024",
#             "first_name": "aklmlamk",
#             "id": 1022053,
#             "registered_on": "03-09-2020 12:55:44",
#             "status": "active",
#             "surname": "a;fa;fm;ml"
#         },
#         {
#             "branch": "Langata",
#             "course": "Bsc.Computer Science",
#             "department": "Computer Science",
#             "expiry_date": "03-09-2024",
#             "first_name": "slfmalfma",
#             "id": 1022054,
#             "registered_on": "03-09-2020 12:55:44",
#             "status": "pending",
#             "surname": "almfa;lmfa;l"
#         },
#         {
#             "branch": "Langata",
#             "course": "Bsc.Computer Science",
#             "department": "Computer Science",
#             "expiry_date": "03-09-2024",
#             "first_name": "Aafaf",
#             "id": 1022055,
#             "registered_on": "03-09-2020 13:04:17",
#             "status": "active",
#             "surname": "Aafaf"
#         }
#     ]
#     g = GenerateReport()
#     print(g.generate_report(data))
